export const deliveryFees: Record<string, number> = {
  "Jardim Copacabana": 3,
  "Santo André": 3,
  "São Paulo": 3,
  "Vivendas da Exposição": 5,
  "Jardinópolis": 5,
  "Jardim das Acácias": 5,
  "Floresta": 5,
  "Padre Herculano Yanes": 7,
  "Marajó": 7,
  "São Judas": 7,
  "Morada Nova": 7,
  "Realengo": 9,
  "Itacolomi": 9,
  "Belvedere": 9,
  "Bela Vista": 9,
  "Jardim Belvedere": 9,
  "Chanadour": 9,
  "São Miguel": 9,
  "Quintino": 10,
  "Planalto": 12,
  "Centro": 15,
  "Vila Santo Antônio": 15,
};
